name: E2E Tests
on:
   # Run on any commit to the #master branch
   push:
      branches: [master, develop]
   # Run on pull requests into the #master branch
   pull_request:
      branches: [master, develop]
   # Allows user to trigger the workflow from GitHub's web UI
   workflow_dispatch:

jobs:
   cypress-test:
      name: Run Tests
      runs-on: ubuntu-latest
      steps:
        - uses: digi-serve/ab-install-action@service-build
        
